version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install .[docs]
    build:
      html:
        - jupyter-book build --builder html docs/
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp --recursive --no-target-directory docs/_build/html $READTHEDOCS_OUTPUT/html
