version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install --verbose .[docs]
    pre_build:
      - jupyter-book config sphinx docs/

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false
